image: quay.io/perfqe/nepta-env:latest

stages:
  - pytest
  - print 
  - code-style
  - mypy
  - build

default:
  before_script:
    - export NETWORK_PERFTEST_ARGS="--help"
    - pipenv install --dev

pytest:
  tags:
    - docker
  stage: pytest
  script: pipenv run pytest --junit-xml=report.xml  
  artifacts:
    expire_in: 1 week
    reports:
      junit: report.xml

nepta-print-conf:
  tags:
    - docker
  stage: print
  script: pipenv run nepta -i example_config . -p -c Default -e fqdn host_1.testlab.org

quotes:
  tags:
    - docker
  stage: pytest
  script: pipenv run unify -c -r ./
  allow_failure: true

black:
  tags:
    - docker
  stage: code-style 
  script: pipenv run black -l 120 --check -S ./

pulp:
  tags:
    - docker
  stage: build
  only:
    - /^v[0-9]*\.[0-9]*\.?[0-9]*$/
  except:
    - branches
  script:
    - pip install pulp-cli
    - pulp config create --username $PULP_USER --password $PULP_PASS --base-url $PULP_URL --api-root /pulp/ --no-verify-ssl
    - python3 setup.py sdist
    - export PKG=$(ls dist)
    - cd dist && pulp python content upload --relative-path $PKG --file $PKG
    - pulp python repository content add --repository nepta --filename $PKG

  artifacts:
    paths:
      - dist
    expire_in: 7 days
