image: fedora

stages:
  - pytest
  - soft
  - advanced
  - ultra

before_script:
  - export NETWORK_PERFTEST_ARGS="--help"
  - dnf -y install python36 python3-pytest git pipenv
  - dnf -y install libselinux-utils tuned python38
  - pip3 install pip -U
  - git config --global http.sslVerify false
  - pipenv install --dev
  - pipenv run env
  - pipenv run pip install .
  - pipenv run pip list


py36:
  tags:
    - docker
  stage: pytest
  script: pipenv run tox -e py36

py37:
  tags:
    - docker
  stage: pytest
  script: pipenv run tox -e py37

py38:
  tags:
    - docker
  stage: pytest
  script: pipenv run tox -e py38

nepta-print-conf:
  tags:
    - docker
  stage: soft
  script: pipenv run nepta -i example_config . -p -c Default -e fqdn host_1.testlab.org

quotes:
  tags:
    - docker
  stage: soft
  script: pipenv run tox -e unify

black:
  tags:
    - docker
  stage: advanced
  needs:
    - quotes
  script: pipenv run tox -e black

flake8:
  tags:
    - docker
  stage: advanced
  needs:
    - quotes
  script: pipenv run tox -e flake8

mypy:
  tags:
    - docker
  stage: ultra
  script: pipenv run pytest --mypy
  allow_failure: true
