image: quay.io/perfqe/nepta-env:latest

stages:
  - pytest
  - print
  - code-style
  - mypy
  - build

pytest:
  tags:
    - docker
  stage: pytest
  script: hatch run test

print-conf:
  tags:
    - docker
  stage: print
  script: hatch run print

code-style:
  tags:
    - docker
  stage: code-style
  script: hatch run lint:style

pytest-mypy:
  tags:
    - docker
  stage: mypy
  script: hatch run mypy:pytest-mypy
  allow_failure: true

mypy-typing:
  tags:
    - docker
  stage: mypy
  script: hatch run mypy:typing
  allow_failure: true

pulp:
  tags:
    - docker
  stage: build
  only:
    - /^v[0-9]*\.[0-9]*\.?[0-9]*$/
  except:
    - branches
  script:
    - pip install pulp-cli
    - pulp config create --username $PULP_USER --password $PULP_PASS --base-url $PULP_URL --api-root /pulp/ --no-verify-ssl
    - python3 setup.py sdist
    - export PKG=$(ls dist)
    - cd dist && pulp python content upload --relative-path $PKG --file $PKG
    - pulp python repository content add --repository nepta --filename $PKG

  artifacts:
    paths:
      - dist
    expire_in: 7 days
