default:
  image: quay.io/perfqe/nepta-env:latest
  tags:
    - shared-podman

include: 
  - project: kernel-performance/perfqe-gitlab-ci-templates
    file: pypi/nexus.yml

stages:
  - pytest
  - code-style
  - mypy
  - publish

pytest:
  stage: pytest
  script: hatch run all:test
  artifacts:
    when: always
    reports:
      junit: report*.xml

print-conf:
  stage: pytest
  script: hatch run print

code-style:
  stage: code-style
  script: hatch run lint:style nepta

pytest-mypy:
  stage: mypy
  script: hatch run mypy:pytest-mypy
  allow_failure: true

mypy-typing:
  stage: mypy
  script: hatch run mypy:typing
  allow_failure: true
