image: quay.io/perfqe/nepta-env:latest

stages:
  - pytest
  - print 
  - code-style
  - mypy
  - build

py36:
  tags:
    - docker
  stage: pytest
  script: tox -e py36

py37:
  tags:
    - docker
  stage: pytest
  script: tox -e py37

py39:
  tags:
    - docker
  stage: pytest
  script: tox -e py39

nepta-print-conf:
  tags:
    - docker
  stage: print
  script: 
    - export NETWORK_PERFTEST_ARGS="--help"
    - pipenv install --dev
    - pipenv run env
    - pipenv run pip install .
    - pipenv run pip list
    - pipenv run nepta -i example_config . -p -c Default -e fqdn host_1.testlab.org

quotes:
  tags:
    - docker
  stage: pytest
  script: tox -e unify
  allow_failure: true

black:
  tags:
    - docker
  stage: code-style 
  script: tox -e black

flake8:
  tags:
    - docker
  stage: code-style 
  script: tox -e flake8

pytest-mypy:
  tags:
    - docker
  stage: mypy 
  script: tox -e pytest-mypy
  allow_failure: true

mypy:
  tags:
    - docker
  stage: mypy 
  script: tox -e mypy
  allow_failure: true

pulp:
  tags:
    - docker
  stage: build
  only:
    - /^v[0-9]*\.[0-9]*\.?[0-9]*$/
  except:
    - branches
  script:
    - pip install pulp-cli
    - pulp config create --username $PULP_USER --password $PULP_PASS --base-url $PULP_URL --api-root /pulp/ --no-verify-ssl
    - python3 setup.py sdist
    - export PKG=$(ls dist)
    - cd dist && pulp python content upload --relative-path $PKG --file $PKG
    - pulp python repository content add --repository nepta --filename $PKG

  artifacts:
    paths:
      - dist
    expire_in: 7 days
