image: quay.io/perfqe/nepta-env:latest

include: 
  - project: kernel-performance/perfqe-gitlab-ci-templates
    file: pypi/pulp.yml

stages:
  - pytest
  - code-style
  - mypy
  - publish

pytest:
  tags:
    - docker
  stage: pytest
  script: hatch run test

print-conf:
  tags:
    - docker
  stage: pytest
  script: hatch run print

code-style:
  tags:
    - docker
  stage: code-style
  script: hatch run lint:style

pytest-mypy:
  tags:
    - docker
  stage: mypy
  script: hatch run mypy:pytest-mypy
  allow_failure: true

mypy-typing:
  tags:
    - docker
  stage: mypy
  script: hatch run mypy:typing
  allow_failure: true
