FROM quay.io/fedora/fedora:latest
RUN dnf -y install python36 python3-pytest python3-pip git libselinux-utils tuned sysstat hatch python39 python310 python311 python312
RUN git config --global http.sslVerify false
COPY . /nepta-core
WORKDIR /nepta-core
RUN pip3 install --upgrade pip
RUN pip3 install hatch
CMD ["hatch", "run", "test"]

